title: Flicktail
email: spring@flicktail.com
description: >-
  Hey, I'm Spring and this blog is about the worlds of furry and cybersecurity.
  Feel free to contact me, promise I won't bite, deer don't even have proper teeth!
url: "https://flicktail.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: spring_buck

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
